In [11]:
import string
import pandas as pd
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.sentiment.util import mark_negation
import chardet

In [3]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rushikesh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rushikesh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rushikesh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Rushikesh\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [4]:
with open('test.csv', 'rb') as file:
    encoding = chardet.detect(file.read())['encoding']
df = pd.read_csv('test.csv', encoding=encoding)
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
4810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df.dropna()
df

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346.0,652860.0,60.0
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797.0,27400.0,105.0
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044.0,2381740.0,18.0
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265.0,470.0,164.0
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272.0,1246700.0,26.0
...,...,...,...,...,...,...,...,...,...
3529,e5f0e6ef4b,"its at 3 am, im very tired but i can`t sleep ...",negative,noon,21-30,Nicaragua,6624554.0,120340.0,55.0
3530,416863ce47,All alone in this old house again. Thanks for...,positive,night,31-45,Niger,24206644.0,1266700.0,19.0
3531,6332da480c,I know what you mean. My little dog is sinkin...,negative,morning,46-60,Nigeria,206139589.0,910770.0,226.0
3532,df1baec676,_sutra what is your next youtube video gonna b...,positive,noon,60-70,North Korea,25778816.0,120410.0,214.0
3533,469e15c5a8,http://twitpic.com/4woj2 - omgssh ang cute n...,positive,night,70-100,North Macedonia,2083374.0,25220.0,83.0

In [6]:
dataset = df.drop(df.columns[[0,3,4,5,6,7,8]],axis = 1)
dataset.head()

                                                text sentiment
0  Last session of the day  http://twitpic.com/67ezh   neutral
1   Shanghai is also really exciting (precisely -...  positive
2  Recession hit Veronique Branquinho, she has to...  negative
3                                        happy bday!  positive
4             http://twitpic.com/4w75p - I like it!!  positive

In [8]:
# Function to preprocess text
def preprocess_text(text):
    # Convert text to lowercase
    lower_text = text.lower()

    cleaned_text = lower_text.translate(str.maketrans('', '', string.punctuation))

    # Tokenize the text
    tokenized_words = word_tokenize(cleaned_text, "english")

    # Remove stopwords
    filtered_words = []
    for word in tokenized_words: 
      if word not in stopwords.words('english'):
        filtered_words.append(word)

    # Lemmatize words
    lemmatized_words = []
    for word in filtered_words:
      word = WordNetLemmatizer().lemmatize(word)
      lemmatized_words.append(word)

    # Join the lemmatized words back into a string
    preprocessed_text = ' '.join(lemmatized_words)
    return preprocessed_text

# Apply preprocessing to each row in the dataframe
df['preprocessed_text'] = df['text'].apply(preprocess_text)

# Display the new dataframe with preprocessed text and sentiment column
final_df = df[['preprocessed_text', 'sentiment']]
final_df.head()

C:\Users\Rushikesh\AppData\Local\Temp\ipykernel_13624\1292955274.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['preprocessed_text'] = df['text'].apply(preprocess_text)

                                   preprocessed_text sentiment
0               last session day httptwitpiccom67ezh   neutral
1  shanghai also really exciting precisely skyscr...  positive
2  recession hit veronique branquinho quit compan...  negative
3                                         happy bday  positive
4                           httptwitpiccom4w75p like  positive

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
from sklearn.svm import SVC

In [10]:
# Step 1: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['preprocessed_text'], df['sentiment'], test_size=0.2, random_state=42)

# Step 2: Vectorize the preprocessed text data
vectorizer = TfidfVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

# Step 3: Train a multi-class classifier
classifier = make_pipeline(TfidfVectorizer(), SVC(kernel='linear'))
classifier.fit(X_train, y_train)

# Step 4: Evaluate the classifier on the testing data
y_pred = classifier.predict(X_test)

# Step 5: Print classification report
print(classification_report(y_test, y_pred))

# Optional: Make predictions on new data
new_texts = ["This movie was fantastic!",
             "I didn't like the plot of this book.",
             "The performance was mediocre."]
new_predictions = classifier.predict(new_texts)
print("Predictions for new texts:")
for text, prediction in zip(new_texts, new_predictions):
    print(f"Text: {text}\nPredicted Sentiment: {prediction}\n")

              precision    recall  f1-score   support

    negative       0.70      0.56      0.62       207
     neutral       0.58      0.73      0.65       286
    positive       0.73      0.62      0.67       214

    accuracy                           0.64       707
   macro avg       0.67      0.63      0.64       707
weighted avg       0.66      0.64      0.64       707

Predictions for new texts:
Text: This movie was fantastic!
Predicted Sentiment: positive

Text: I didn't like the plot of this book.
Predicted Sentiment: negative

Text: The performance was mediocre.
Predicted Sentiment: neutral